title: OCTO Chti
lang: fr
email: chti@octo.com
url: 'https://qdesmedt.github.io'
baseurl: '/chti.octo.com'
tel: +33 6 83 27 24 73
twitter:
    username: octochti
    card: summary
github_username: OCTOTechnology
social:
    name: OCTO chti
    links:
        - https://twitter.com/OCTOchti
        - https://github.com/OCTOTechnology
logo: /brand.png
google_analytics: UA-134710918-1

markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
